### ISSUE TITLE
Discuss: Basic Integration

### ISSUE THREAD

**Issue by peterkeen** [masteringmodernpayments/book#3]
- Create a basic Rails application
- Do the simplest Stripe integration
- Learn how to deploy to Heroku

**Comment by jonskirk** [comment]
Hi Pete - I am working through your book, and it looks great so far. I have my app working, and deployed to Heroku, and am now on the Stripe integration. One question: you don't mention how to set the environment variables locally (you have a link for Heroku). What is your recommendation for handling environment variables locally vs on Heroku? FYI I am on OS X.

**Comment by gpxl** [comment]
@jonskirk I use Figaro for local config. Makes things dead simple. https://github.com/laserlemon/figaro

**Comment by abatko** [comment]
@peterkeen in the *Basic Setup* section, why do you suggest `source 'https://code.stripe.com'` rather than the typical `source 'https://rubygems.org'`? - ([the `stripe` gem is available at RubyGems](https://rubygems.org/gems/stripe))

**Comment by Jaibles** [comment]
Hi @peterkeen thanks for the great book. Just running into an issue trying to create a product. 
`Paperclip::Errors::MissingRequiredValidatorError in ProductsController#create` on line 24 of `products_controller.rb` `@product = Product.new(product_params)`

Found this on S.O. but unsure where to implement the solution having tried various ways.
http://stackoverflow.com/questions/21897725/papercliperrorsmissingrequiredvalidatorerror-with-rails-4

**Comment by peterkeen** [comment]
@abatko It's a recommendation from Stripe, actually. It predates rubygems.org having an https endpoint and is less relevant now, but it's nice to go straight to the source.

**Comment by zenners** [comment]
Hey Pete,

I get this error when running rake test. I'm totally new to testing and all the other tests fail. I'm not entirely sure how to go about it. More importantly the transctions controller is where im focused.

TransactionsControllerTest#test_should_post_create:
NameError: uninitialized constant ActiveSupport::TestCase::StripeMock
    test/test_helper.rb:10:in `block in class:TestCase'

this is whats in my transction controller

require 'test_helper'
require 'stripe_mock'
class TransactionsControllerTest < ActionController::TestCase
test "should post create" do
    product = Product.create(
      permalink: 'test_product',
      price:     100
    )
    email = 'michael@example.com'
    token = 'tok_test'

```
post :create, email: email, stripeToken: token

assert_not_nil assigns(:sale)
assert_not_nil assigns(:sale).stripe_id
assert_equal product.id, assigns(:sale).product_id
assert_equal email, assigns(:sale).email
```

  end
end

**Comment by peterkeen** [comment]
`require 'stripe_mock'` should be toward the top of `test/test_helper.rb.
Sorry about that.

**Comment by ghost** [comment]
Hi Pete, 
Great book! I only have the basic version ;) so the code samples might be different from what's in the book, but fwiw I had to make a couple changes to get the transactionsController test to work: 

in test_helper.rb:

```
    def stripe_helper
        StripeMock.create_test_helper
    end
```

in transactions_controller_test.rb, changed the post:

```
    email: 'you@example.com'
    post :create, stripeEmail: email, stripeToken: stripe_helper.generate_card_token, permalink: product.permalink
```

(also needed to add mocha to the Gemfile)

**Comment by peterkeen** [comment]
@dlambeth thanks! I'll have those changes in the next version. Also, do you mean `email = 'you@example.com'` ?

**Comment by ghost** [comment]
indeed, that's what I meant :)

**Comment by micahtaylor** [comment]
Getting an error on the download link:
URI::InvalidURIError in TransactionsController#download
the scheme http does not accept registry part: :80 (or bad hostname?)

``` ruby
resp = HTTParty.get(@sale.product.file.url)
```

**Comment by systemnate** [comment]
I am also getting an error on the download link.  In my Heroku log, it says:

```
2015-09-01T19:01:10.325640+00:00 app[web.1]: Processing by TransactionsController#download as HTML
2015-09-01T19:01:10.325663+00:00 app[web.1]:   Parameters: {"guid"=>"67rbdy"}
2015-09-01T19:01:10.327711+00:00 app[web.1]:   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
2015-09-01T19:01:10.330496+00:00 app[web.1]:   Product Load (0.8ms)  SELECT  "products".* FROM "products" WHERE "products"."id" = $1 LIMIT 1  [["id", 1]]
2015-09-01T19:01:10.333511+00:00 app[web.1]: 
2015-09-01T19:01:10.333513+00:00 app[web.1]: Errno::ECONNREFUSED (Connection refused - connect(2)):
2015-09-01T19:01:10.333514+00:00 app[web.1]:   app/controllers/transactions_controller.rb:45:in `download'
2015-09-01T19:01:10.333515+00:00 app[web.1]: 
2015-09-01T19:01:10.333516+00:00 app[web.1]: 
2015-09-01T19:01:10.397440+00:00 app[web.1]: Started GET "/download/67rbdy" for 173.27.229.45 at 2015-09-01 19:01:10 +0000
2015-09-01T19:01:10.403170+00:00 app[web.1]:   Sale Load (0.8ms)  SELECT  "sales".* FROM "sales" WHERE "sales"."guid" = $1 LIMIT 1  [["guid", "67rbdy"]]
2015-09-01T19:01:10.406610+00:00 app[web.1]: Completed 500 Internal Server Error in 7ms (ActiveRecord: 2.4ms)
```

Any idea as to why?

**Comment by systemnate** [comment]
I also had to change the test to what @dlambeth  said in order for it to work.  How frequently do you release a new version?  I like the concept of the book, but it seems like there have been a lot of things I've had to change and figure out to get it to work.

**Comment by EricRicketts** [comment]
Peter,
  Is there anything different I need to do with mandrill?  In this chapter you have `heroku addons:add mandrill:starter` (btw `addons:add` is deprecated you now need `addons:create`).  Running the above command I get `!    Couldn't find either the add-on service or the add-on plan of "mandrill:starter".`  I went to my Heroku add on page for Mandrill https://devcenter.heroku.com/articles/mandrill and found no mention of a free option.  It seems I can only use the basic option now -> `heroku addons:create mandrill:basic` for $9.95/month.  Obviously, I would prefer not to do this only for the sake of the tutorial.  What can I do to keep moving forward in the book?

**Comment by peterkeen** [comment]
Just create an account on https://mandrill.com/ and they'll give you 2k
free messages. Postmark (https://postmarkapp.com/) will give you 25k
messages free, and would work just as well.

Either way, set the environment variables (i.e. username, password, server,
port) and everything should just work.

**Comment by EricRicketts** [comment]
Pete,
That was fast!!  I am very new to Rails programming so where to set the environment variables? Do so in `config/environments/production.rb`?  Which is the next code snippet in your book?  Yes I already signed up for a Mandrill account.

**Comment by peterkeen** [comment]
Well, the application in the book is designed for Heroku, so when you
deploy to Heroku you'll set them with `heroku config:add WHATEVER=123
ANDEVER=456`. I like Figaro for maintaining settings that can be overridden:

https://github.com/laserlemon/figaro

I don't really document it in the book, but it's on my list of things to do.

**Comment by EricRicketts** [comment]
Pete,
I cannot get my first test to pass.  I am referring to the `TransactionsControllerTest` at the end of this chapter, _Basic Integration_.

Again I am new to Rails.  I usually use Rspec but switching to TestUnit should not be too difficult.  Here is the error:

`TransactionsControllerTest#test_should_post_create:
ActionController::UrlGenerationError: No route matches {:action=>"create", :controller=>"transactions", :email=>"pete@example.com", :stripeToken=>"tok_test"}
    test/functional/transactions_controller_test.rb:11:in`block in class:TransactionsControllerTest'`

Obviously, the test is not reaching the `#create` action in the TransactionsController.  I would like to get all of my tests to pass, even though the application is working right now when I navigate to `localhost:3000/buy/{my_permalink}`.  Could it be some idiosyncrasy with `skip_before_action :authenticate_user!, only: [:new, :create]` in the TransactionsController with regard to testing?

Eric

**Comment by Academy-of-One** [comment]
Hello, maybe you can help with an issue I am having. I am using your book as a (rough) way to switch my app from checkout to stripe.js. 

I am switching out stripe checkout with stripe.js. Everything works when I type in a card except it never goes through. Whenever I click submit I am getting an error that says: 

    Cannot charge a customer that has no active card 

I've tried using both the test card and a real credit card number and both of them are giving me the same error. Here is my stripe.rb:

    class ChargesController < ApplicationController
    	before_action :authenticate_user!
    	def new
    	end
    
    	def create
    	  # Amount in cents
    	  @amount = 500
    
    	  customer = Stripe::Customer.create(
    	    :email => params[:stripeEmail],
    	    :source  => params[:stripeToken]
    	  )
    
    	  Stripe.api_key = 'sk_test_string'
    
    charge = Stripe::Charge.create(
    :amount => 1000,
    :customer => customer.id,
    :currency => "usd",
    :card => params[:stripeToken] # replace full card details with the string token from our params
    )
    
    	rescue Stripe::CardError => e
    	  flash[:error] = e.message
    	  redirect_to new_charge_path
    	end
    end

Here is my haml with the embeded javascript:

    .well{:style => "margin-left: 0px; position: relative; min-width: 650px; min-height: 180px; max-height: 180px"}
        = form_tag charges_path :id => 'payment-form' do
          .row
          .row
            %div
              %label.control-label{:for => "number"} Card Number
              %input#number{"data-stripe" => "number", :pattern => "[\\d ]*", :placeholder => "**** **** **** ****", :size => "20", :style => "width: 18em", :type => "text", :maxlength => "16"}/
          .row
            %div
              %label.control-label{:for => "cvc"} CVC
              %input#cvc{"data-stripe" => "cvc", :pattern => "\\d*", :placeholder => "***", :size => "3", :style => "width: 3em", :type => "text"}/
              = image_tag "credit.png"
            %div
              %label.control-label Exp (MM/YYYY)
              %input#exp-month{"data-stripe" => "exp-month", :pattern => "\\d*", :placeholder => "MM", :size => "2", :type => "text"}/
              %span /
              %input#exp-year{"data-stripe" => "exp-year", :pattern => "\\d*", :placeholder => "YYYY", :size => "4", :type => "text"}/
          .row
            .price
              5.00
            %div
              %button.btn.btn-primary.btn-large{:type => "submit"} Buy Now
    :javascript
    Stripe.setPublishableKey('pk_test_string');
    $('#payment-form').submit(function(event) {
      var form = $(this);
      form.find('button').prop('disabled', true);
      Stripe.createToken(form, stripeResponseHandler);
      return false;
    });
    function stripeResponseHandler(status, response) {
      var form = $('#payment-form');
      if (response.error) {
        form.find('.payment-errors').text(response.error.message);
        form.find('button').prop('disabled', false);
      } else {
        var token = response.id;
        form.append($('<input type="hidden" name="stripeToken">').val(token));
        form.get(0).submit();
      }

Edit:
 I went into the error logs on stripe and it's giving me this:

    error:
        message: "Cannot charge a customer that has no active card"
        type: "card_error"
        param: "card"
        code: "missing"

But I have filled out the card error and it should be working. If it helps I am using test keys.

Thank you so much for the help

**Comment by dgreen22** [comment]
Hi Pete,

So I'm building an app and forgive me if you've explained this in further chapters, but I don't see this.  I can't find a solution anywhere that explains how to have two fixed prices for two packages that can be purchased, mainly the `amount` section the Transactions Controller Charge create action. So If I have 2 packages, Package 1 - $10, Package 2 - $20 - I have two separate simple Stripe buttons set-up for each package right now (I'm sure not ideal solution, but using it for now until I get better hang of complex checkout), but run into problems in the controller as I can't hard code a dollar amount and these two prices are assigned to a product so I can't use something like `product.price`.  Any thoughts on the simplest way of doing this?  I figure it probably involves some JS and/or a Package model but wanted to know your thoughts.   Thanks!

**Comment by peterkeen** [comment]
I would personally set up two different product instances that only vary on
price. You could also use some sort of Package model, but that seems like
maybe overcomplicating the problem.

**Comment by dgreen22** [comment]
Thanks Pete.  Appreciate it!

On Mon, Feb 22, 2016 at 2:58 PM, Pete Keen notifications@github.com wrote:

> I would personally set up two different product instances that only vary on
> price. You could also use some sort of Package model, but that seems like
> maybe overcomplicating the problem.
> 
> On Mon, Feb 22, 2016 at 2:43 PM, dgreen22 notifications@github.com
> wrote:
> 
> > Hi Pete,
> > 
> > So I'm building an app and forgive me if you've explained this in further
> > chapters, but I don't see this. I can't find a solution anywhere that
> > explains how to have two fixed prices for two packages that can be
> > purchased, mainly the amount section the Transactions Controller Charge
> > 
> > ## create action. So If I have 2 packages, Package 1 - $10, Package 2 - $20
> > 
> > I have two separate simple Stripe buttons set-up for each package right
> > now
> > (I'm sure not ideal solution, but using it for now until I get better
> > hang
> > of complex checkout), but run into problems in the controller as I can't
> > hard code a dollar amount and these two prices are assigned to a product
> > so
> > I can't use something like product.price. Any thoughts on the simplest
> > way of doing this? I figure it probably involves some JS and/or a
> > Packages
> > model but wanted to know your thoughts. Thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/masteringmodernpayments/book/issues/3#issuecomment-187344627
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/masteringmodernpayments/book/issues/3#issuecomment-187357011
> .

## 

"I've never got much accomplished assuming the worse in other people" -
Barack Obama

**Comment by dgreen22** [comment]
Hi Pete,

Quick question.  Wouldn't I have to create a model in order to run the
product instances you suggested?  Sorry if this is a rookie question - I'm
new to web dev and I'm learning RoR.

Thanks!

David

On Mon, Feb 22, 2016 at 2:58 PM, Pete Keen notifications@github.com wrote:

> I would personally set up two different product instances that only vary on
> price. You could also use some sort of Package model, but that seems like
> maybe overcomplicating the problem.
> 
> On Mon, Feb 22, 2016 at 2:43 PM, dgreen22 notifications@github.com
> wrote:
> 
> > Hi Pete,
> > 
> > So I'm building an app and forgive me if you've explained this in further
> > chapters, but I don't see this. I can't find a solution anywhere that
> > explains how to have two fixed prices for two packages that can be
> > purchased, mainly the amount section the Transactions Controller Charge
> > 
> > ## create action. So If I have 2 packages, Package 1 - $10, Package 2 - $20
> > 
> > I have two separate simple Stripe buttons set-up for each package right
> > now
> > (I'm sure not ideal solution, but using it for now until I get better
> > hang
> > of complex checkout), but run into problems in the controller as I can't
> > hard code a dollar amount and these two prices are assigned to a product
> > so
> > I can't use something like product.price. Any thoughts on the simplest
> > way of doing this? I figure it probably involves some JS and/or a
> > Packages
> > model but wanted to know your thoughts. Thanks!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/masteringmodernpayments/book/issues/3#issuecomment-187344627
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/masteringmodernpayments/book/issues/3#issuecomment-187357011
> .

## 

"I've never got much accomplished assuming the worse in other people" -
Barack Obama

**Comment by peterkeen** [comment]
Yep, you'd need a Product model.

**Comment by dgreen22** [comment]
Perfect.  Thanks!

On Wed, Mar 2, 2016 at 5:46 PM, Pete Keen notifications@github.com wrote:

> Yep, you'd need a Product model.
> 
> On Wed, Mar 2, 2016 at 5:44 PM, dgreen22 notifications@github.com wrote:
> 
> > Hi Pete,
> > 
> > Quick question. Wouldn't I have to create a model in order to run the
> > product instances you suggested? Sorry if this is a rookie question - I'm
> > new to web dev and I'm learning RoR.
> > 
> > Thanks!
> > 
> > David
> > 
> > On Mon, Feb 22, 2016 at 2:58 PM, Pete Keen notifications@github.com
> > wrote:
> > 
> > > I would personally set up two different product instances that only
> > > vary
> > > on
> > > price. You could also use some sort of Package model, but that seems
> > > like
> > > maybe overcomplicating the problem.
> > > 
> > > On Mon, Feb 22, 2016 at 2:43 PM, dgreen22 notifications@github.com
> > > wrote:
> > > 
> > > > Hi Pete,
> > > > 
> > > > So I'm building an app and forgive me if you've explained this in
> > > > further
> > > > chapters, but I don't see this. I can't find a solution anywhere that
> > > > explains how to have two fixed prices for two packages that can be
> > > > purchased, mainly the amount section the Transactions Controller
> > > > Charge
> > > > create action. So If I have 2 packages, Package 1 - $10, Package 2 -
> > > > 
> > > > ## $20
> > > > 
> > > > I have two separate simple Stripe buttons set-up for each package
> > > > right
> > > > now
> > > > (I'm sure not ideal solution, but using it for now until I get better
> > > > hang
> > > > of complex checkout), but run into problems in the controller as I
> > > > can't
> > > > hard code a dollar amount and these two prices are assigned to a
> > > > product
> > > > so
> > > > I can't use something like product.price. Any thoughts on the
> > > > simplest
> > > > way of doing this? I figure it probably involves some JS and/or a
> > > > Packages
> > > > model but wanted to know your thoughts. Thanks!
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > 
> > https://github.com/masteringmodernpayments/book/issues/3#issuecomment-187344627
> > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/masteringmodernpayments/book/issues/3#issuecomment-187357011
> > 
> > > .
> > 
> > ## 
> > 
> > "I've never got much accomplished assuming the worse in other people" -
> > Barack Obama
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/masteringmodernpayments/book/issues/3#issuecomment-191476147
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/masteringmodernpayments/book/issues/3#issuecomment-191476666
> .

## 

"I've never got much accomplished assuming the worse in other people" -
Barack Obama

**Comment by emilkarl** [comment]
Seems like Heroku stopped supporting Mandrill, might be because of the the Mandrill changes that require (http://blog.mailchimp.com/important-changes-to-mandrill/) a payed Mailchimp subscription (https://elements.heroku.com/addons#email-sms). Would be nice with a change to another email service?

**Comment by peterkeen** [comment]
Thanks! I'll change it to point at SparkPost, which is what Mandrill is
officially recommending.

**Comment by emilkarl** [comment]
Ok cool, I know SendGrid is probably as simple as Mandrill and is available as an addon from Heroku as well.

**Comment by taylorscollon** [comment]
This all works, but when it comes to downloading the actual product a number is being appended to the filename extension when I click the download button. So for example 'ebook.pdf' becomes 'ebook.pdf-14629372'. In my S3 bucket, the extension is just .pdf. 

The result of this is that the downloaded PDF can't be opened unless I manually remove the appended number from the extension. When I do that, I can open it no problem.

Any idea what might be causing this issue?

**Comment by patrickbense** [comment]
@peterkeen in regards to using SparkPost instead of Mandrill, has this been updated in the paid copy of your book? I am just running through the free sample and ran into the issue with Mandrill going paid. I do plan on purchasing the book but just wanted to see if this change was made. Digging everything so far!

**Comment by peterkeen** [comment]
Not yet. I'll do that update soon.

**Comment by RuNpiXelruN** [comment]
@peterkeen , thanks for taking the time to create this fantastic resource..it's greatly appreciated! 

Does anyone know why i'd be getting this error when trying to download? It works fine until I hit download? 
`Errno::ECONNREFUSED in TransactionsController#download`
`Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)`
   `resp = HTTParty.get(@sale.product.file.url)`

**Comment by dgreen22** [comment]
@peterkeen Hi Peter - I'm getting this error message I've been trying to solve for a couple days now.
`` Error:
TransactionsControllerTest#test_should_post_create:
ActiveRecord::RecordNotFound: Couldn't find Product
``

The issue appears to be happening here in my Transactions controller:
`` product = Product.find_by!(
      permalink: params[:permalink] ``
    )

Here's my Transactions Test Controller:
`` test "should post create" do
    product = Product.create(
      permalink: 'test_product',
      price:  100,
      name: 'ovo',
      description: 'done lets finish'
    )

    email = 'test@example.com'
    token = 'tok_test'

    post buy_url(product.permalink), params: {email: email, stripeToken: token}
  end ``

Cheers,

David

**Comment by dgreen22** [comment]
For anyone using Rails 5 - the new syntax in the Transactions Test Controller is:

`post buy_url(product.permalink), params: {stripeEmail: email, stripeToken: stripe_helper.generate_card_token}`

`post :create, email: email, stripeToken: token` I don't believe works anymore.

**Comment by JeanBaptisteW** [comment]
I bought the book last year.
In first chapter we see how to sell a downlodable book, but how to sell contents articles (like https://www.masteringmodernpayments.com/read). I would like sell only content articles.
Thank you.

**Comment by peterkeen** [comment]
You can generalize the instructions by tying a devise-powered User record
to each sale.

**Comment by om341** [comment]
Thanks for the thorough course!  I just joined and made it through this first module, however seem to be getting a Stripe form submission error upon pressing "Pay Now" that says (see attached screenprints):
{"error":"Stripe token can't be blank"}

I'm new to Rails and not quite sure how to track down / debug the source of the issue.  Any help would be much appreciated. Thanks

![om341_stripe_checkout](https://cloud.githubusercontent.com/assets/27559328/25063728/7656479a-21ba-11e7-8d4a-e62cd96827cf.png)

![stripe token can t be blank error](https://cloud.githubusercontent.com/assets/27559328/25063735/8ed33e18-21ba-11e7-802e-15c5f1e3faec.png)

**Comment by teamagility** [comment]
Hey @peterkeen thanks for the guide  - it's awesome. One question - I am getting this error back when adding Sparkpost:

Couldn't find either the add-on service or the add-on plan of
 ▸    "sparkpost:free".

Thanks
Shaun

**Comment by peterkeen** [comment]
It looks like Sparkpost doesn't offer a free plan anymore. Try using the
Mailgun add-on:

https://elements.heroku.com/addons/mailgun

You'll have to adjust the names of the environment variables when setting
up the smtp config, but other than that it should be basically the same.

**Comment by teamagility** [comment]
Hi @peterkeen I'll do that, thanks. Strange, because Sparkpost has a whole thing about how they offer 100k free emails a month. Still gets an error message from the basic command:

heroku addons:create sparkpost

gets
Couldn't find either the add-on service or the add-on plan of "sparkpost".
