### ISSUE TITLE
Discuss: Security and PCI Compliance

### ISSUE THREAD

**Issue by peterkeen** [masteringmodernpayments/book#4]
- Learn about PCI compliance
- Generate and install an SSL certificate
- Set up Rails security tools

**Comment by gpxl** [comment]
+1 on the CloudFlare suggestion.

**Comment by maxrosecollins** [comment]
When I run `rake check` I get the error 

```
rake aborted!
Don't know how to build task 'rails_best_practices'
```

**Comment by peterkeen** [comment]
Could you paste what you have in `lib/tasks/security.rake`?

On Thu, Feb 19, 2015 at 12:37 PM, Max Rose-Collins <notifications@github.com

**Comment by maxrosecollins** [comment]
task :brakeman do
  sh "brakeman -q -z"
end

**Comment by peterkeen** [comment]
Looks like you missed the steps in the "Rails Best Practices". You can
either do those or comment/remove the `
Rake::Task['rails_best_practices'].invoke` line in `task :check`.

On Thu, Feb 19, 2015 at 12:40 PM, Max Rose-Collins <notifications@github.com

**Comment by maxrosecollins** [comment]
yep, my mistake.

also getting another error when i run the tests.

```
TransactionsControllerTest#test_should_post_create:
    NameError: undefined local variable or method `email' for #<TransactionsControllerTest:0x007f95611f6708>
test/functional/transactions_controller_test.rb:9:in `block in <class:TransactionsControllerTest>'
```

**Comment by peterkeen** [comment]
Thanks. I'll get that taken care of in the next release. In the mean time,
you can add this to the test, before the `post`:

``` ruby
    email = 'pete@example.com'
    token = 'tok_test'
```

On Thu, Feb 19, 2015 at 12:52 PM, Max Rose-Collins <notifications@github.com

**Comment by maxrosecollins** [comment]
okay now I am getting 

ActionController::UrlGenerationError: No route matches {:action=>"create", :controller=>"transactions", :email=>"pete@example.com", :stripeToken=>"tok_test"}
    test/functional/transactions_controller_test.rb:12:in `block in class:TransactionsControllerTest'

**Comment by zenners** [comment]
Hey Pete,

I get this error when running rake test. I'm totally new to testing and all the other tests fail. I'm not entirely sure how to go about it. More importantly the transctions controller is where im focused.

TransactionsControllerTest#test_should_post_create:
NameError: uninitialized constant ActiveSupport::TestCase::StripeMock
    test/test_helper.rb:10:in `block in <class:TestCase>'


this is whats in my transction controller

require 'test_helper'
require 'stripe_mock'
class TransactionsControllerTest < ActionController::TestCase
test "should post create" do
    product = Product.create(
      permalink: 'test_product',
      price:     100
    )
    email = 'michael@example.com'
    token = 'tok_test'

    post :create, email: email, stripeToken: token

    assert_not_nil assigns(:sale)
    assert_not_nil assigns(:sale).stripe_id
    assert_equal product.id, assigns(:sale).product_id
    assert_equal email, assigns(:sale).email
  end
end

**Comment by dxypher** [comment]
@maxrosecollins I'm getting the same error:

TransactionsControllerTest#test_should_post_create:
ActionController::UrlGenerationError: No route matches {:action=>"create", :controller=>"transactions", :email=>"pete@example.com", :stripeToken=>"tok_test"}
    test/functional/transactions_controller_test.rb:13:in `block in class:TransactionsControllerTest'

Were you able to solve this?

**Comment by gregblass** [comment]
You should mention lets encrypt here since its free. Super easy to setup with the automated installer.
