### ISSUE TITLE
Discuss: Handling Webhooks

### ISSUE THREAD

**Issue by peterkeen** [masteringmodernpayments/book#7]
- Handling webhooks with Stripe Event
- Testing your event handling
- Learn how to send PDF receipts

**Comment by maxrosecollins** [comment]
Hi,

Im getting this error when running the tests.

```
1) Error:
WebhooksTest#test_charge_created:
ActionView::MissingTemplate: Missing template stripe_mailer/receipt with "mailer". Searched in:
  * "stripe_mailer"

    app/mailers/stripe_mailer.rb:20:in `receipt'
    config/initializers/stripe_event.rb:14:in `block (2 levels) in <top (required)>'
    test/integration/webhooks_test.rb:8:in `block in <class:WebhooksTest>'
```

**Comment by zenners** [comment]
I've been scratching my head for a few hours on the email feature. 

I have the mandrill add on from heroku. and have the ENV variables set their as well.

I have this setting in my production.rb file

config.action_mailer.delivery_method = :smtp
   config.action_mailer.smtp_settings = {
    address:        'smtp.mandrillapp.com',
    port:           587,
    user_name:      ENV['MANDRILL_USERNAME'],
    password:       ENV['MANDRILL_APIKEY'],
    domain:         'heroku.com',
    authentication: :plain

This is my stripe_mailer.rb

class StripeMailer < ActionMailer::Base
  default from: 'cu.michaels@gmail.com'

  def admin_dispute_created(charge)
    @charge = charge
    @sale = Sale.find_by(stripe_id: @charge.id)
    if @sale
      mail(to: 'cu.michaels@gmail.com', subject: "Dispute created on charge #{@sale.guid} (#{charge.id})").deliver
    end
  end

  def receipt(charge)
    @charge = charge
    @sale = Sale.find_by!(stripe_id: @charge.id)
    mail(to: @sale.email, subject: "Thanks for purchasing #{@sale.product.name}")
  end
end

I'm guessing its something to do with the default? I never authorized my gmail to send anything, but whats the heroku/mandrill default? I tested it on Stripe's website and got a 401 (not authorized)

Also questio, how does it know which template to send once it comes from stripe_mailer.rb?

**Comment by boomshadow** [comment]
I have a thought about your initial Webhook validation. Is this necessary if I'm setting up StripeEvent's secured endpoint?  https://github.com/integrallis/stripe_event#securing-your-webhook-endpoint

The idea is that only Stripe can post to my listener because they are the only ones that know the secret key. StripeEvent will reject all others. I no longer need the extra call to Stripe to ask them if the event is legitimate or not, right? This ought to save me from creating the stripe_webhooks table with all those entries, right?

**Comment by nikolay12** [comment]
You are listing the content of "app/views/admin_charge_succeeded.html.erb". Shouldn't the path be, instead, "app/views/stripe_mailer/admin_charge_succeeded.html.erb"?

**Comment by peterkeen** [comment]
Yes! Thank you for the bug report. I'll have it fixed in the next release.

**Comment by gpxl** [comment]
Am I doing something wrong? It appears that the id in the call below is expected to set the event id to "abc123".

```
StripeMock.mock_webhook_event('charge.succeeded', id: 'abc123')
```

But it's setting the data object id.

```
   -[[:id, "test_evt_1"],
   - [:created, 1326853478],
   - [:livemode, false],
   - [:type, "charge.succeeded"],
   - [:object, "event"],
   - [:data,
   -  [[:object,
   -    [[:id, "abc123"],
   -     [:object, "charge"],
   -     [:created, 1380933505],
```

Causing this assertion to fail

```
assert_equal 'abc123', StripeWebhook.last.stripe_id
```

**Comment by colinxchristmas** [comment]
Just in case anyone else comes across this. I had to change my line of the test as follows.

` assert_equal event.id, StripeWebhook.last.stripe_id `
